### ISSUE TITLE
Readme clarification about when filters are triggered

### ISSUE THREAD

**Issue by JanStevens** [omohokcoj/filterable#2]
Hello,

I'm having a difficult time grasping when a filter is triggered when giving some params. 

Given following search params

```elixir
search = %{q: %{name: "playpass", barcode: "1234"}, sort: "name", order: "desc", page: 1, per_page: 6}
list = [%{"barcode" => "915580318","name" => "PlayPass Scanout"}, ...]
```

With the following filters

```elixir
@options param: [q: :name], cast: &String.downcase/1
filter name(list, %{name: name}) do
  IO.inspect "SEARCHING NAME"
  list  
end

  @options param: [q: :barcode], cast: &String.downcase/1
  filter barcode(list, %{barcode: barcode}) do
    IO.inspect "SEARCHING barcode"
    list
  end
```

When running the filters, nothing is printed in the console, but I expect both to be run. So some questions that pop up that I couldn't find in the readme:

1. Is the filter name of any importance? Does it need to match the param name? Or can it be anything? Does it need to be unique?
2. How do `@options` relate to the filter name and the params? I do notice that the original nesting is not kept, meaning everything is flattend
3. How to deal with nested search like in the above example? It's quite common to have a form for searching so everything is then namespaced

Thanks! I really like this project since it does not assume anything about your framework or how you want to filter data

**Comment by omohokcoj** [comment]
1. Yeah, if filter name has the same name as the expected filter parameter then you don't need to specify `param: <name>` explicitly:
```elixir
defmodule Filter do
  use Filterable.DSL

  @options cast: &String.downcase/1
  filter name(list, name) do
    IO.inspect "filter param is '#{name}'"
    list
  end
end

search = %{name: "test"}
Filter.apply_filters(list, search) # iex> "filter param is 'test'"
```

2. `@options` attribute could take effect only on filter defined below it. It's not related to filter name or it's incoming params, it's just the way to customize filter behaviour.

3. We have `top_param` filter option that allows to fetch nested params. 
Here is your example but with `top_param`:
```elixir
defmodule Filter do
  use Filterable.DSL

  @options top_param: :q, cast: &String.downcase/1
  filter name(list, value) do
    IO.inspect "SEARCHING NAME"
    list
  end

  @options top_param: :q, cast: &String.downcase/1
  filter barcode(list, value) do
    IO.inspect "SEARCHING barcode"
    list
  end
end
```
As you can see, there is no need to specify `param: <name>` explicitly because filter has the same name as the incoming parameter.

Your filter was not triggered because of pattern matching (not matching 😄 ).
In your case filter value would be simply `name` not `%{name: name}` so filterable can't find function that match this pattern and silently skips it.
So you can treat filters like regular elixir functions with pattern matching and guard clauses.

@JanStevens hope this answer will help you, thanks for your interest 😜 
I'll update README shortly to make things a bit clearer.

**Comment by JanStevens** [comment]
Haa `top_param` that explains it ofcourse! Will try it out directly, thanks for the clarification on the naming of the filters related to the param. Explains a lot :)
